INSERT INTO "Users" ("name", "email", "password", "role", "created_at", "updated_at")
VALUES 
('Ahmad Jauhari', 'ahmadjauhari@gmail.com', 'jauhari123', 'admin', DEFAULT, DEFAULT),
('Muhamad Candra', 'candraaja@gmail.com', 'candr427', 'admin', DEFAULT, DEFAULT),
('Rafi Kirana', 'kiranaraafi@gmail.com', 'brorafi', 'admin', DEFAULT, DEFAULT),
('Citra Sari', 'citrabksi@gmail.com', 'itscitra2', 'admin', DEFAULT, DEFAULT),
('Rizky Pratama', 'pratamarizky@gmail.com', 'rizkyers80', 'admin', DEFAULT, DEFAULT),
('Mada Rahadian', 'rahadiana@gmail.com', 'rahadian1', 'fundraiser', DEFAULT, DEFAULT),
('Aldean Tegar', 'aldean@gmail.com', 'deankentuung2', 'fundraiser', DEFAULT, DEFAULT),
('Ananda Maulana', 'maulanaaa1@gmail.com', 'ananda1922', 'fundraiser', DEFAULT, DEFAULT),
('Rizal Bakhri', 'rizallk@gmail.com', 'bakhriizal', 'fundraiser', DEFAULT, DEFAULT),
('Lilis Handayani', 'lilisza4@gmail.com', 'tealilis1', 'fundraiser', DEFAULT, DEFAULT),
('Muhamad Reza', 'rezaaaja@gmail.com', 'mhmdrza3', 'donatur', DEFAULT, DEFAULT),
('Ahmad Muzaki', 'muzakiahmad@gmail.com', 'muzakipro1st', 'donatur', DEFAULT, DEFAULT),
('Alfahri', 'fachrian@gmail.com', 'fachrians', 'donatur', DEFAULT, DEFAULT),
('Muhamad Dani Lukman', 'danyyluchman@gmail.com', 'imdannye', 'donatur', DEFAULT, DEFAULT),
('Eka Heryawan', 'ekaherywan5@gmail.com', 'ekaherywn9', 'donatur', DEFAULT, DEFAULT),
('Rama Amiru Zaki', 'ramazaky@gmail.com', 'qwertyrama', 'donatur', DEFAULT, DEFAULT),
('Yusup Rayaka', 'yusuprayaka@gmail.com', 'lakess', 'donatur', DEFAULT, DEFAULT),
('Deden Alfariza', 'alfarizadeden@gmail.com', 'iamdedentea', 'donatur', DEFAULT, DEFAULT),
('Dini Safitri', 'safittrdini@gmail.com', 'dinyytiny', 'donatur', DEFAULT, DEFAULT),
('Daffa Leviando', 'levianda1@gmail.com', 'daffacity93', 'donatur', DEFAULT, DEFAULT),
('Azril Saiful', 'saifuza0gmail.com', 'azrielsaifful', 'donatur', DEFAULT, DEFAULT),
('Muhamad Sauqi', 'sauqiiy@gmail.com', 'sauuqiman', 'donatur', DEFAULT, DEFAULT),
('Sintia Clara', 'clarasint@gmail.com', 'sintaaja22', 'donatur', DEFAULT, DEFAULT),
('Annisa Febriyanti', 'febriyyanw@gmail.com', 'aniizzaweb', 'donatur', DEFAULT, DEFAULT),
('Agus Saputra', 'saputeraagee@gmail.com', 'agussaputts', 'donatur', DEFAULT, DEFAULT),
('Arif Budiman', 'budimannaja@gmail.com', 'masbudi11', 'donatur', DEFAULT, DEFAULT),
('Ratna Dewi Shinta', 'ratnnwis@gmail.com', 'shintaya', 'donatur', DEFAULT, DEFAULT),
('Maya Fitriyani', 'mayaseppt@gmail.com', 'fitmayop1', 'donatur', DEFAULT, DEFAULT),
('Sandy Zakia', 'zakysand47@gmail.com', 'zakkyaja', 'donatur', DEFAULT, DEFAULT),
('Fajar Kurniawan', 'zarnywan@gmail.com', 'mangkurni0', 'donatur', DEFAULT, DEFAULT);

select * from Users;
