INSERT INTO "Verification_Logs" ("campaign_id", "user_id", "admin_id", "verification_date", "status", "reason", "created_at")
VALUES
(1, 1, 1, GETDATE(), 'approved', NULL, GETDATE()),
(1, 2, 2, GETDATE(), 'rejected', 'Dokumen tidak lengkap', GETDATE()),
(2, 3, 3, GETDATE(), 'approved', NULL, GETDATE()),
(2, 4, 1, GETDATE(), 'approved', NULL, GETDATE()),
(3, 5, 2, GETDATE(), 'rejected', 'Kampanye tidak sesuai kriteria', GETDATE()),
(3, 6, 3, GETDATE(), 'approved', NULL, GETDATE()),
(4, 7, 1, GETDATE(), 'approved', NULL, GETDATE()),
(4, 8, 2, GETDATE(), 'rejected', 'Permohonan tidak valid', GETDATE()),
(5, 9, 3, GETDATE(), 'approved', NULL, GETDATE()),
(5, 10, 1, GETDATE(), 'approved', NULL, GETDATE()),
(6, 11, 2, GETDATE(), 'rejected', 'Tidak memenuhi syarat', GETDATE()),
(6, 12, 3, GETDATE(), 'approved', NULL, GETDATE()),
(7, 13, 1, GETDATE(), 'approved', NULL, GETDATE()),
(7, 14, 2, GETDATE(), 'approved', NULL, GETDATE()),
(8, 15, 3, GETDATE(), 'rejected', 'Diperlukan revisi', GETDATE()),
(8, 16, 1, GETDATE(), 'approved', NULL, GETDATE()),
(9, 17, 2, GETDATE(), 'approved', NULL, GETDATE()),
(9, 18, 3, GETDATE(), 'rejected', 'Bukti tidak lengkap', GETDATE()),
(10, 19, 1, GETDATE(), 'approved', NULL, GETDATE()),
(10, 20, 2, GETDATE(), 'rejected', 'Informasi tidak akurat', GETDATE()),
(11, 21, 3, GETDATE(), 'approved', NULL, GETDATE()),
(11, 22, 1, GETDATE(), 'approved', NULL, GETDATE()),
(12, 23, 2, GETDATE(), 'rejected', 'Kampanye sudah berakhir', GETDATE()),
(12, 24, 3, GETDATE(), 'approved', NULL, GETDATE()),
(13, 25, 1, GETDATE(), 'approved', NULL, GETDATE()),
(13, 26, 2, GETDATE(), 'approved', NULL, GETDATE()),
(14, 27, 3, GETDATE(), 'rejected', 'Tidak memenuhi kriteria', GETDATE()),
(14, 28, 1, GETDATE(), 'approved', NULL, GETDATE()),
(15, 29, 2, GETDATE(), 'approved', NULL, GETDATE()),
(15, 30, 3, GETDATE(), 'rejected', 'Dokumen tidak valid', GETDATE()),
(16, 1, 1, GETDATE(), 'approved', NULL, GETDATE()),
(17, 2, 2, GETDATE(), 'approved', NULL, GETDATE()),
(18, 3, 3, GETDATE(), 'rejected', 'Perlu revisi', GETDATE()),
(19, 4, 1, GETDATE(), 'approved', NULL, GETDATE()),
(20, 5, 2, GETDATE(), 'rejected', 'Data tidak lengkap', GETDATE());
